### PR TITLE
Update lib-common to contain .generation fix

### PR DESCRIPTION
**Pull request by mrkisaolamb**

### CODE REVIEW

**Comment by gibizer** [comment]
> Update lib-common to contain .generation fix

From which module?

**Review by gibizer — APPROVED** [review]
We need this as there are test cases defined in mariadb-operator that are called from the service operators and the shared uses a lib-common helper that is updated with .observedGeneration support.

**Comment by gibizer** [comment]
/test mariadb-operator-build-deploy-kuttl
 prow should work now

**Review by stuggi — APPROVED** [review]
/lgtm

**Pull request merged**
