### PR TITLE
Webhook for default images

### PR DESCRIPTION
**Pull request by abays**
Default container images are now handled via env vars and internal webhooks. This defaulting logic will in turn later be integrated with OpenStack Operator via webhooks there that use the new defaulting mechanism (while at the same time disabling the MariaDB service operator internal webhooks in that context).

### CODE REVIEW

**Comment by abays** [comment]
> @abays: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/mariadb-operator-build-deploy-kuttl 	[9e18211](https://github.com/openstack-k8s-operators/mariadb-operator/commit/9e18211f812983a68109c3ba80ea2222f95c9924) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_mariadb-operator/84/pull-ci-openstack-k8s-operators-mariadb-operator-master-mariadb-operator-build-deploy-kuttl/1640736675313225728) 	false 	`/test mariadb-operator-build-deploy-kuttl`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=mariadb-operator&pr=84). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:abays).

CI failure is unrelated to this PR:

```
+ oc exec -it pod/mariadb-openstack -- mysql -uroot $'-p\236\351e' -e 'show databases;'
Error from server (NotFound): pods "mariadb-openstack" not found
```

/test mariadb-operator-build-deploy-kuttl

**Comment by abays** [comment]
> > @abays: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> > Test name 	Commit 	Details 	Required 	Rerun command
> > ci/prow/mariadb-operator-build-deploy-kuttl 	[9e18211](https://github.com/openstack-k8s-operators/mariadb-operator/commit/9e18211f812983a68109c3ba80ea2222f95c9924) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_mariadb-operator/84/pull-ci-openstack-k8s-operators-mariadb-operator-master-mariadb-operator-build-deploy-kuttl/1640747787454779392) 	false 	`/test mariadb-operator-build-deploy-kuttl`
> > [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=mariadb-operator&pr=84). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:abays).
> 
> CI will fail for this PR and all current/future PRs until we fix bundle size concerns. OpenStack operator has become too large and can no longer be installed, which thus causes CI logic to fail. We have begun to address the problem [1].
> 
> [1] [openstack-k8s-operators/openstack-operator#260](https://github.com/openstack-k8s-operators/openstack-operator/pull/260)

https://github.com/openstack-k8s-operators/openstack-operator/pull/260 has been merged. Retrying.

/test mariadb-operator-build-deploy-kuttl

**Comment by abays** [comment]
@dprince @stuggi @dciabrin This PR is passing CI now thanks to Dan's bundle break-out changes.  Would someone mind reviewing?

**Review by dprince — APPROVED** [review]

**Pull request merged**
