### PR TITLE
Run go work sync during make gowork

### PR DESCRIPTION
**Pull request by gibizer**
This will ensure that the go.mod files in the root and in ./api will not have different versions from the same dependency. Such divergence known to cause troubles when generating manifests in different environments.

### CODE REVIEW

**Comment by gibizer** [comment]
I believe that the kuttl failure is unrelated to this change:
```
    case.go:366: resource MariaDB:openstack/openstack: .spec.containerImage: value mismatch, expected: quay.io/tripleozedcentos9/openstack-mariadb:current-tripleo != actual: unused
```

**Comment by abays** [comment]
> I believe that the kuttl failure is unrelated to this change:
> 
> ```
>     case.go:366: resource MariaDB:openstack/openstack: .spec.containerImage: value mismatch, expected: quay.io/tripleozedcentos9/openstack-mariadb:current-tripleo != actual: unused
> ```

Might be caused by this change: https://github.com/openstack-k8s-operators/install_yamls/pull/148

**Comment by gibizer** [comment]
> > I believe that the kuttl failure is unrelated to this change:
> > ```
> >     case.go:366: resource MariaDB:openstack/openstack: .spec.containerImage: value mismatch, expected: quay.io/tripleozedcentos9/openstack-mariadb:current-tripleo != actual: unused
> > ```
> 
> Might be caused by this change: [openstack-k8s-operators/install_yamls#148](https://github.com/openstack-k8s-operators/install_yamls/pull/148)

Good point. So I guess that change break the ability to deploy individual operators via install_yamls.

**Comment by gibizer** [comment]
> > > I believe that the kuttl failure is unrelated to this change:
> > > ```
> > >     case.go:366: resource MariaDB:openstack/openstack: .spec.containerImage: value mismatch, expected: quay.io/tripleozedcentos9/openstack-mariadb:current-tripleo != actual: unused
> > > ```
> > 
> > 
> > Might be caused by this change: [openstack-k8s-operators/install_yamls#148](https://github.com/openstack-k8s-operators/install_yamls/pull/148)
> 
> Good point. So I guess that change break the ability to deploy individual operators via install_yamls.



> > > I believe that the kuttl failure is unrelated to this change:
> > > ```
> > >     case.go:366: resource MariaDB:openstack/openstack: .spec.containerImage: value mismatch, expected: quay.io/tripleozedcentos9/openstack-mariadb:current-tripleo != actual: unused
> > > ```
> > 
> > 
> > Might be caused by this change: [openstack-k8s-operators/install_yamls#148](https://github.com/openstack-k8s-operators/install_yamls/pull/148)
> 
> Good point. So I guess that change break the ability to deploy individual operators via install_yamls.

Fix is up https://github.com/openstack-k8s-operators/install_yamls/pull/215

**Comment by gibizer** [comment]
It seems it is not needed.

**Pull request closed without merging**
