### PR TITLE
Use Galera in default KUTTL assertion

### PR DESCRIPTION
**Pull request by abays**
Galera is now the default for `install_yamls` and thus for the KUTTL tests it executes.  This fixes the default sample assertion for KUTTL to look for a `Galera` CR and its associated `StatefulSet` instead of a `MariaDB` CR and its associated `Pod`.

I tested this locally with `MARIADB_KUTTL_DIR=/home/abays/rh/mariadb-operator/tests/kuttl/tests make keystone_kuttl` (which uses the MariaDB KUTTL targets).  Without my changes there was the expected failure, but with them the test succeeded.

### CODE REVIEW

**Comment by kajinamit** [comment]
Thanks Andrew for spotting this.

We should also update how the file is linked to the tests directory. Now the file is used in mariadb_deploy but we should use it in galera_deploy.

```
$ ls -lah tests/kuttl/tests/*_deploy/
tests/kuttl/tests/galera_deploy/:
total 28K
drwxr-xr-x. 1 tkajinam tkajinam  274 May 30 12:44 .
drwxr-xr-x. 1 tkajinam tkajinam   54 May 30 12:44 ..
lrwxrwxrwx. 1 tkajinam tkajinam   31 May 30 12:44 00-create-secret.yaml -> ../../common/create_secret.yaml
-rw-r--r--. 1 tkajinam tkajinam 1.9K Jun 26 20:20 01-assert.yaml
-rw-r--r--. 1 tkajinam tkajinam  196 May 30 12:44 01-deploy_galera.yaml
-rw-r--r--. 1 tkajinam tkajinam  445 Jun 26 20:19 02-assert.yaml
-rw-r--r--. 1 tkajinam tkajinam  191 May 30 12:44 02-scale_down_galera.yaml
-rw-r--r--. 1 tkajinam tkajinam  288 May 30 12:44 03-cleanup_galera.yaml
-rw-r--r--. 1 tkajinam tkajinam  755 May 30 12:44 03-errors.yaml
drwxr-xr-x. 1 tkajinam tkajinam   36 May 30 12:44 deploy

tests/kuttl/tests/mariadb_deploy/:
total 20K
drwxr-xr-x. 1 tkajinam tkajinam 200 May 30 12:44 .
drwxr-xr-x. 1 tkajinam tkajinam  54 May 30 12:44 ..
lrwxrwxrwx. 1 tkajinam tkajinam  31 May 30 12:44 00-create-secret.yaml -> ../../common/create_secret.yaml
lrwxrwxrwx. 1 tkajinam tkajinam  42 Jan 19 17:19 01-assert.yaml -> ../../common/assert_sample_deployment.yaml
-rw-r--r--. 1 tkajinam tkajinam 197 May 30 12:44 01-deploy-mariadb.yaml
-rw-r--r--. 1 tkajinam tkajinam 171 May 30 12:44 02-cleanup-mariadb.yaml
-rw-r--r--. 1 tkajinam tkajinam 292 May 30 12:44 02-errors.yaml
drwxr-xr-x. 1 tkajinam tkajinam  36 May 30 12:44 deploy
```

**Comment by cescgina** [comment]
@kajinamit is right, we have two test cases for mariadb, one with galera and the other with mariadb, we should switch the new `assert_common_deployment.yaml` to point to the galera one, and keep the old contents to the `mariadb_deploy` test case

**Comment by abays** [comment]
Thanks guys.  I will make the suggested changes.

**Comment by abays** [comment]
> Thanks guys. I will make the suggested changes.

Galera's `01-assert.yaml` now links to `common/assert-sample-deployment.yaml`.  MariaDB's `01-assert.yaml` now contains the old content of `common/assert-sample-deployment.yaml` and is thus no longer a symlink.

**Review by cescgina — COMMENTED** [review]
looks good to me

**Review by stuggi — APPROVED** [review]
/lgtm

**Pull request merged**
