### PR TITLE
Move database module content from lib-common to /api

### PR DESCRIPTION
**Pull request by gibizer**
This is needed to resolve a circular dependency.

### CODE REVIEW

**Comment by gibizer** [comment]
/retest 
cert manager issue is fixed

**Comment by gibizer** [comment]
/test mariadb-operator-build-deploy-kuttl
```
{  failed to wait for the created cluster claim to become ready: timed out waiting for the condition}
```

**Comment by gibizer** [comment]
/unhold
There are example adaptation PRs ([nova](https://github.com/openstack-k8s-operators/nova-operator/pull/554), [keystone](https://github.com/openstack-k8s-operators/keystone-operator/pull/323))  showing that this works

**Review by fmount — APPROVED** [review]
As per the conversation on slack, I think it's a good idea keeping the functions used for envTests aligned w/ the API, so we can see consistency between envTests execution and a job when we bump the api dependency that we include on a different operator.
+1 from me

**Review by stuggi — APPROVED** [review]
/lgtm

**Pull request merged**
