### PR TITLE
Drops the finalizer to delete the DB

### PR DESCRIPTION
**Pull request by dprince**
This drops the DB delete finalizer.

Leaving in the Job and script/template to delete the database so we can follow up with a "DB purge" feature in the future.

### CODE REVIEW

**Review by stuggi — COMMENTED** [review]
wouldn't it be easier re the follow up purge feature, which I'd really like to have fore dev, to just add the purge parameter now and just add a condition for the dbDeleteJob?

**Comment by stuggi** [comment]
> wouldn't it be easier re the follow up purge feature, which I'd really like to have fore dev, to just add the purge parameter now and just add a condition for the dbDeleteJob?

we could also just have a  different behavior on this between mariadb-operator for dev and the galera one for prod?

**Comment by dprince** [comment]
> wouldn't it be easier re the follow up purge feature, which I'd really like to have fore dev, to just add the purge parameter now and just add a condition for the dbDeleteJob?

We can do the purge feature now. However unlike how the finalizer, the purge feature actually requires changes in all operators in order for it to work correctly. I can add it here however for the time being. And in any case if we do switch things out for a galara-operator it would go away then anyway.

**Comment by stuggi** [comment]
> > wouldn't it be easier re the follow up purge feature, which I'd really like to have fore dev, to just add the purge parameter now and just add a condition for the dbDeleteJob?
> 
> We can do the purge feature now. However unlike how the finalizer, the purge feature actually requires changes in all operators in order for it to work correctly. I can add it here however for the time being. And in any case if we do switch things out for a galara-operator it would go away then anyway.

ack, lets merge it and then do a follow up either in the operator or in install_yamls

**Review by stuggi — APPROVED** [review]
/lgtm

**Pull request merged**
