### PR TITLE
Fix pre-commit findings

### PR DESCRIPTION
**Pull request by gibizer**

### CODE REVIEW

**Review by stuggi — APPROVED** [review]
/lgtm

**Comment by stuggi** [comment]
```
# github.com/openstack-k8s-operators/openstack-operator/apis/core/v1beta1
apis/core/v1beta1/openstackcontrolplane_webhook.go:316:13: template.Default undefined (type "github.com/openstack-k8s-operators/mariadb-operator/api/v1beta1".GaleraSpec has no field or method Default)
apis/core/v1beta1/openstackcontrolplane_webhook.go:357:13: template.Default undefined (type "github.com/openstack-k8s-operators/mariadb-operator/api/v1beta1".MariaDBSpec has no field or method Default)
make: *** [Makefile:106: vet] Error 2
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2023-07-20T05:40:03Z"}
error: failed to execute wrapped command: exit status 2
```

**Comment by gibizer** [comment]
> ```
> # github.com/openstack-k8s-operators/openstack-operator/apis/core/v1beta1
> apis/core/v1beta1/openstackcontrolplane_webhook.go:316:13: template.Default undefined (type "github.com/openstack-k8s-operators/mariadb-operator/api/v1beta1".GaleraSpec has no field or method Default)
> apis/core/v1beta1/openstackcontrolplane_webhook.go:357:13: template.Default undefined (type "github.com/openstack-k8s-operators/mariadb-operator/api/v1beta1".MariaDBSpec has no field or method Default)
> make: *** [Makefile:106: vet] Error 2
> {"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2023-07-20T05:40:03Z"}
> error: failed to execute wrapped command: exit status 2
> ```

That seems unrelated to this PR but at the same time seems scarry

**Comment by gibizer** [comment]
There are kuttl tests ongoing in other PRs like https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_mariadb-operator/62/pull-ci-openstack-k8s-operators-mariadb-operator-main-mariadb-operator-build-deploy-kuttl/1681944128981569536 so we will see if this issue is happening regurarly.

**Comment by gibizer** [comment]
/test mariadb-operator-build-deploy-kuttl
```
  * could not run steps: step mariadb-operator-build-deploy-kuttl failed: failed to wait for the created cluster claim to become ready: timed out waiting for the condition 
```

**Pull request closed without merging**
