### PR TITLE
Use time.Duration for timeout

### PR DESCRIPTION
**Pull request by kajinamit**
instead of int. This allows us to use more fine grained timeout value such as 0.1, and encodes the unit in the type itself.

Depends-On: openstack-k8s-operators/lib-common#155

### CODE REVIEW

**Comment by kajinamit** [comment]
The failure doesn't look relevant to this change ...

```

run golangci-lint
  Running [/home/runner/golangci-lint-1.51.1-linux-amd64/golangci-lint run --out-format=github-actions --timeout 5m] in [] ...
  Error: undefined: RegisterFailHandler (typecheck)
  Error: undefined: RunSpecsWithDefaultAndCustomReporters (typecheck)
  Error: undefined: Reporter (typecheck)
```

**Review by gibizer — APPROVED** [review]
looks good

**Comment by gibizer** [comment]
the missing go mod tidy run causing the failures here as well. fixed it now. I expect it to pass CI now.

**Review by gibizer — APPROVED** [review]

**Pull request merged**
